language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx-18mode
  - rbx-19mode
before_install:
  - 'rm -rf $rvm_path/gems/*/{bin,gems}/rubygems-bundler-* $rvm_path/gems/*/bin/ruby_*_wrapper'
  - hash -r
install: gem install dtf
script: dtf --text test/dtf/*
notifications:
  irc:
    channels:
      - "irc.freenode.org#rubygems-bundler"
  email:
    recipients:
      - mpapis@gmail.com
    on_failure: change
matrix:
  allow_failures:
    - rvm: rbx-18mode
    - rvm: rbx-19mode
